### ISSUE TITLE
Add to packagist

### ISSUE THREAD

**Issue by iwazaru** [payplug/payplug-php#1]
It would be great to registrer this library as a composer/packagist package.

We could install/update it easily from the cli with:

    composer require payplug/payplug-php

More info: http://blog.grossi.io/2013/creating-your-first-composer-packagist-package/

**Comment by David-Guillot** [comment]
:+1: 

And while you're at it, you can remove composer.lock, it's [almost useless for a library](https://getcomposer.org/doc/02-libraries.md#lock-file) ;)

**Comment by fbureau** [comment]
It is coming very soon :) 

Thanks a lot for your feedback!

**Comment by iwazaru** [comment]
:+1:

**Comment by HerveDelvaux** [comment]
The composer autoload : "psr-0" is wrong [pull requests](https://github.com/payplug/payplug-php/pull/2)

**Comment by fbureau** [comment]
HerveDelvaux it should be fixed in version 2.2.0 of payplug-php. This new version implement nom PSR-0 and PSR-4. Did you test it ? Is it working for you ?

**Comment by HerveDelvaux** [comment]
We have updated 2.2. it works for us.
