### ISSUE TITLE
IPN : \Payplug\Notification::treat throw exception 

### ISSUE THREAD

**Issue by B-Poignant** [payplug/payplug-php#13]
Hi, 

For 48 hours, we experience  some errors on our IPN, 7 times same error.

We have this Exception : 

Argument 1 passed to Payplug\Resource\Payment::fromAttributes() must be of the type array, null given, called in /Payplug/Resource/Payment.php on line 112

Last error JSON : 
`{"is_live":true,"notification":{"response_code":null,"url":"URL"},"created_at":1512247451,"amount":817,"is_3ds":false,"save_card":false,"is_paid":true,"metadata":{"transaction_id":"SOME DATA"},"failure":null,"card":{"id":null,"country":"FR","exp_month":1,"exp_year":2018,"brand":"MasterCard","last4":"1111","metadata":null},"is_refunded":false,"amount_refunded":0,"object":"payment","currency":"EUR","customer":{"email":"EMAIL","address1":null,"country":null,"address2":null,"city":null,"postcode":null,"last_name":"NAME","first_name":"NAME"},"hosted_payment":{"paid_at":1512247506,"cancel_url":"URL","return_url":"URL","payment_url":"https:\/\/secure.payplug.com\/pay\/6fZZoQYTNylNIJIIWWoyg9"},"id":"pay_6fZZoQYTNylNIJIIWWoyg9"}`

I change some data to avoid showing client information but original JSON is valid and if i retry to call \Payplug\Notification::treat with this JSON, no exception throwed.

**Comment by nilleroux** [comment]
Thanks for opening a ticket about this. We indeed had a partial production outage that might have caused this. We are really sorry for the inconvenience.

Be sure to not return a 2xx HTTP status in such cases, so that the IPN can be tried again later.
