### ISSUE TITLE
API to the Payplug Products ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [payplug/payplug-php#15]
Hi,

About : https://portal.payplug.com/#/products

Do you plan to expose an API to interact directly with "Products" ?

For instance, i'd find usefull to have a mean to check the price of a "Product" so i could automatically synchronise it with my webpage, and also to be able to dynamically choose the redirection-page associated with the "Product". (and also quantity in stock)

**Comment by nilleroux** [comment]
Hi,
Thank you very much for reaching out. I'm sorry, but we haven't planed to expose product information through our API. Although this might happen someday, it's really unlikely it happens soon enough. The only alternative for you at the moment is to implement the logic on your side. Sorry.
