### ISSUE TITLE
custom metadata with 0 chr len breaks CSS in portal.payplug.com

### ISSUE THREAD

**Issue by SuperUserNameMan** [payplug/payplug-php#16]
Hi,

````
$metadata = [
	'tel1' => "0123456789",
	'tel2' => "", // <-------------- empty string here

	'vendeur' => "Hulk",
];

$paiement = \Payplug\Payment::create(array(

	'amount'    => 1000,
	'currency'  => 'EU',
		
	'save_card' => false,
		
	'customer'  => $customer,
		
	'hosted_payment' => [
		'return_url' => $return_url,
		'cancel_url' => $cancel_url,
	],
		
	'notification_url' => $notification_url,
		
	'metadata' => $metadata,
));

````

See code above : ``$metadata['tel2']`` is an empty string.

See screenshot below : When displaying the payment at https://portal.payplug.com/#/payments/xxxxx  the CSS is broken (Firefox 59.0.2)

![payplug_20180419_1559](https://user-images.githubusercontent.com/9801802/38996944-911c4868-43ec-11e8-9cb9-d8ccdf4aa912.jpg)

**Comment by nilleroux** [comment]
Hi,
Nice catch. Thank you. This should be fixed in the next release!
