### ISSUE TITLE
PrestaShop module?

### ISSUE THREAD

**Issue by mcdado** [payplug/payplug-php#18]
Hello, I was looking for the repository of the PrestaShop module, which is freely available on your website. I have a bug report for it, where should is send it to?

**Comment by mcdado** [comment]
Up?

**Comment by Dixeat** [comment]
Hello,
Sorry for the delay, the actual Prestashop module is not open source but we will release soon a new reunified PrestaShop module on versions 1.6 & 1.7. This new version will be completely open source and open to issues and pull requests.

**Comment by mcdado** [comment]
Thanks!
