### ISSUE TITLE
Proprietary ?

### ISSUE THREAD

**Issue by David-Guillot** [payplug/payplug-php#4]
Hello,

The composer.json (hence Packagist) says this lib is proprietary. Is it on purpose? If so, can you publish an EULA (are PRs allowed, etc.)? Or did you forget to set an (FL)OSS license?

Thanks

**Comment by nilleroux** [comment]
Hi!

The licence should be MIT. This will be fixed in the upcoming release (this week or next week).

Thanks for your report.
